version: '3.3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - '8001:27017'
    volumes:
      - gameslot-mongo:/data/db
    logging:
      driver: none

  backend:
    build: ./game-slot/backend
    container_name: gameslot-api
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/gameslot
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - '5000:5000'

  # frontend:
  #   build: ./game-slot/frontend
  #   container_name: gameslot-site
  #   depends_on:
  #     - backend
  #   ports:
  #     - '8080:8080'

volumes:
  gameslot-mongo:
